services:

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: feeds-backend
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: feeds-frontend
    depends_on:
      - backend
    ports:
      - "5175:80"
    restart: unless-stopped
